spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Crud-aula
    username: postgres
    password: 3Speranca
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true